[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "speech-to-text-transcription-tool"
version = "0.1.0"
description = "Speech to Text Transcription Tool & Dictation Hub"
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
dependencies = [
    "typer",
    "pydantic",
    "requests",
    "fastapi",
    "uvicorn",
    "language-tool-python",
    "pyyaml",
    "dateparser",
    "python-dotenv",
    "websockets",
    "pytest",
    "freezegun",
    "python-dotenv",
    "ipython>=8.18.1",
]

[project.optional-dependencies]
optimization = [
    "optuna",
    "jiwer",
    "torch",
    "sounddevice",
    "numpy",
    "torchaudio"
]

[project.scripts]
dictation-hub = "dictation_hub.cli:app"

[tool.hatch.build.targets.wheel]
packages = ["src/dictation_hub"]
